SGA.Web/Models/ErrorViewModel.cs
namespace SGA.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SGA.Web/Controllers/BusAdmController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SGA.Application.Base;
using SGA.Application.Dtos.Configuration.Bus;
using SGA.Application.Interfaces;
using SGA.Application.Services;

namespace SGA.Web.Controllers
{
    public class BusAdmController : Controller
    {
        private readonly IBusService _busService;

        public BusAdmController(IBusService busService)
        {
            _busService = busService;
        }
        // GET: BusAdmController
        public async Task<ActionResult> Index()
        {
           
            ServiceResult result = await _busService.GetBuses();

            if (!result.Success)
            {
                ViewBag.ErrorMessage = result.Message;
                return View();
            }

            return View(result.Data);

           
        }

        // GET: BusAdmController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            ServiceResult result = await _busService.GetBusById(id);

            if (!result.Success)
            {
                ViewBag.ErrorMessage = result.Message;
                return View();
            }

            return View(result.Data);
        }

        // GET: BusAdmController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusAdmController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateBusDto createBusDto)
        {
            try
            {
                ServiceResult result = await _busService.CreateBus(createBusDto);

                if (!result.Success)
                {
                    ViewBag.ErrorMessage = result.Message;
                    return View();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BusAdmController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ServiceResult result = await _busService.GetBusById(id);

            if (!result.Success)
            {
                ViewBag.ErrorMessage = result.Message;
                return View();
            }

            return View(result.Data);
        }

        // POST: BusAdmController/Edit/5-
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UpdateBusDto updateBusDto)
        {
       

            try
            {
                updateBusDto.UsuarioActualizacion = 1; // TODO: Replace with actual user ID from session or context
                updateBusDto.FechaActualizacion = DateTime.Now;
                ServiceResult result = await _busService.UpdateBus(updateBusDto);

                if (!result.Success)
                {
                    ViewBag.ErrorMessage = result.Message;
                    return View();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
    }
}

SGA.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SGA.Web.Models;
using System.Diagnostics;

namespace SGA.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SGA.Web/Views/BusAdm/Create.cshtml
@model SGA.Application.Dtos.Configuration.Bus.CreateBusDto

@{
    ViewData["Title"] = "Create";
}

<h1>Bus Adm sgsfg</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroPlaca" class="control-label"></label>
                <input asp-for="NumeroPlaca" class="form-control" />
                <span asp-validation-for="NumeroPlaca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadPiso1" class="control-label"></label>
                <input asp-for="CapacidadPiso1" class="form-control" />
                <span asp-validation-for="CapacidadPiso1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadPiso2" class="control-label"></label>
                <input asp-for="CapacidadPiso2" class="form-control" />
                <span asp-validation-for="CapacidadPiso2" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponible" /> @Html.DisplayNameFor(model => model.Disponible)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioCreacion" class="control-label"></label>
                <input asp-for="UsuarioCreacion" class="form-control" />
                <span asp-validation-for="UsuarioCreacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SGA.Web/Views/BusAdm/Details.cshtml
@model SGA.Application.Dtos.Configuration.Bus.GetBusDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdBus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdBus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPlaca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPlaca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CapacidadPiso1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadPiso1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CapacidadPiso2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacidadPiso2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponible)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdBus }) |
    <a asp-action="Index">Back to List</a>
</div>

SGA.Web/Views/BusAdm/Edit.cshtml
@model SGA.Application.Dtos.Configuration.Bus.GetBusDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="IdBus" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroPlaca" class="control-label"></label>
                <input asp-for="NumeroPlaca" class="form-control" />
                <span asp-validation-for="NumeroPlaca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadPiso1" class="control-label"></label>
                <input asp-for="CapacidadPiso1" class="form-control" />
                <span asp-validation-for="CapacidadPiso1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacidadPiso2" class="control-label"></label>
                <input asp-for="CapacidadPiso2" class="form-control" />
                <span asp-validation-for="CapacidadPiso2" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponible" /> 
                    @Html.DisplayNameFor(model => model.Disponible)
                </label>
            </div>
          
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SGA.Web/Views/BusAdm/Index.cshtml
@model IEnumerable<SGA.Application.Dtos.Configuration.Bus.GetBusDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Adm Bus</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
              
                IdBus
            </th>
            <th>
              
                NumeroPlaca
            </th>
            <th>
                Nombre
            </th>
            <th>
                CapacidadPiso1
            </th>
            <th>
                CapacidadPiso2
            </th>
            <th>

                Disponible
            </th>
            <th>
                FechaCreacion
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                   
                    @item.IdBus
                </td>
                <td>
                 
                    @item.NumeroPlaca
                </td>
                <td>
                  
                    @item.Nombre
                </td>
                <td>
                  
                    @item.CapacidadPiso1    
                </td>
                <td>
                  
                    @item.CapacidadPiso2
                </td>
                <td>
                   
                    @item.Disponible
                </td>
                <td>
                    @item.FechaCreacion
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.IdBus }) |
                    @Html.ActionLink("Details", "Details", new { id = item.IdBus })
                    

                </td>
            </tr>
        }
    </tbody>
</table>

SGA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGA.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SGA.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGA.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusAdm" asp-action="Index">Buses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SGA.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>